export const CATEGORY_LIST = [
  { name: "All", value: "" },
  { name: "Frontend", value: "Frontend" },
  { name: "Backend", value: "Backend" },
  { name: "Mobile", value: "Mobile" },
  { name: "Infra", value: "Infra" },
  { name: "AI", value: "AI" },
  { name: "ML", value: "ML" },
  { name: "Data", value: "Data" },
  { name: "Design", value: "Design" },
  { name: "Security", value: "Security" },
  { name: "QA", value: "QA" },
  { name: "Team", value: "Team" },
  { name: "Service", value: "Service" },
  { name: "Brand", value: "Brand" },
  { name: "Money", value: "Money" },
  { name: "Event", value: "Event" },
  { name: "ETC", value: "ETC" },
];
